### PR TITLE
PR roll up. Instances, web3 upgrade, class based, augment data.

### PR DESCRIPTION
**Pull request by crueber**
This is a breaking change. When bringing in the dependency, one now needs to call the function.

`const abiDecoder = require('abi-decoder')()`

This allows me to have more than one decoder.

### CODE REVIEW

**Comment by crueber** [comment]
I recognize that this is a very opinionated change. If it's not what you're looking for, I'll understand and publish my own fork to use.

**Comment by crueber** [comment]
Replaced webpack and replaced with parcel.

**Comment by denisgranha** [comment]
Hey @crueber :)
What do you want to obtain by different instances? there shouldn't be collisions in the decoder due to the nature of how method ids are generated in ethereum, well, at least, shouldn't be frequent, first four hex characters of a sha3

**Comment by crueber** [comment]
I'm going to close this PR and open another one that points back to this one, because I can't find a way to switch branches that are being pulled from my repo, because I need to keep working on my updates.

**Pull request closed without merging**
