### PR TITLE
Upgrade web3 to 1.2.1 and out of beta

### PR DESCRIPTION
**Pull request by spalladino**
Upgrades dependency on web3 to use 1.2.1 instead of beta.37

### CODE REVIEW

**Comment by denisgranha** [comment]
👏 Thanks!

**Comment by spalladino** [comment]
That was fast, thanks @denisgranha! Do you know when you would be releasing a new version to npm with this upgrade?

**Comment by denisgranha** [comment]
done https://www.npmjs.com/package/abi-decoder/v/2.1.0

**Comment by spalladino** [comment]
Again, that was fast. Thanks @denisgranha!!

**Pull request merged**
